### PR TITLE
Fixes login problem with IE11

### PR DESCRIPTION
**Pull request by SirBisgaard**
This will fixed login issue with IE11 on the portal (ASP.NET Zero).

### CODE REVIEW

**Comment by ismcagdas** [comment]
Thanks @SirBisgaard, it will be in the next release.

**Comment by SirBisgaard** [comment]
I also have a change to the abp-web-resources package but i dont have access to it... But the jquery ajax extension file (abp.jquery.js) needs changes too.
Here is a snippet of the change i made. 

    abp.ajax = function (userOptions) {
        userOptions = userOptions || {};

        var options = $.extend({}, abp.ajax.defaultOpts, userOptions);
        options.beforeSend = function(xhr) {
           xhr.setRequestHeader("Pragma", "no-cache");
           xhr.setRequestHeader("Cache-Control", "no-cache");
           xhr.setRequestHeader("If-Modified-Since", "Wed, 21 Oct 2020 07:28:00 GMT");
        };

**Comment by SirBisgaard** [comment]
Found the repo... 👍 
aspnetboilerplate/bower-abp-resources

**Comment by ismcagdas** [comment]
Hi @SirBisgaard ,

As I noticed, you set a static future date for If-Modified-Since header value.
Does it have to be a future date ? If so, can you set it programatically ?

Thanks.

**Comment by SirBisgaard** [comment]
The date should be today +1. :)

**Pull request merged**
